name: Update Manga Data
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install axios

      - name: Run Script with Retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 3
          max_attempts: 15 # Increased attempts since random is truly random now
          retry_wait_seconds: 2
          command: node update_manga.js

      - name: Commit and Push
        run: |
          git config --global user.name "MangaBot"
          git config --global user.email "bot@github.com"
          git add manga_data.json
          git commit -m "Auto-update: New Manga Added"
          git push
          
